### ISSUE TITLE
Build fails to compile with Boost 1.69

### ISSUE THREAD

**Issue by correaa** [rwols/yaml-archive#3]
` error: ‘class boost::array<A, 10>’ has no member named ‘serialize’`

```
[ 39%] Building CXX object test/narrow/CMakeFiles/test_yaml-archive_yml.dir/__/arrays.cpp.o
In file included from /home/correaa/soft/yaml-archive/test/A.hpp:33,
                 from /home/correaa/soft/yaml-archive/test/arrays.cpp:1:
/usr/include/boost/serialization/access.hpp: In instantiation of ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::yaml_oarchive; T = boost::array<A, 10>]’:
/usr/include/boost/serialization/serialization.hpp:68:22:   required from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::yaml_oarchive; T = boost::array<A, 10>]’
/usr/include/boost/serialization/serialization.hpp:126:14:   required from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::yaml_oarchive; T = boost::array<A, 10>]’
/usr/include/boost/archive/detail/oserializer.hpp:153:40:   required from ‘void boost::archive::detail::oserializer<Archive, T>::save_object_data(boost::archive::detail::basic_oarchive&, const void*) const [with Archive = boost::archive::yaml_oarchive; T = boost::array<A, 10>]’
/usr/include/boost/archive/detail/oserializer.hpp:106:1:   required from ‘class boost::archive::detail::oserializer<boost::archive::yaml_oarchive, boost::array<A, 10> >’
/usr/include/boost/archive/detail/oserializer.hpp:258:13:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/archive/detail/oserializer.hpp:539:18:   required from ‘void boost::archive::save(Archive&, T&) [with Archive = boost::archive::yaml_oarchive; T = const boost::array<A, 10>]’
/usr/include/boost/archive/detail/common_oarchive.hpp:71:22:   required from ‘void boost::archive::detail::common_oarchive<Archive>::save_override(T&) [with T = const boost::array<A, 10>; Archive = boost::archive::yaml_oarchive]’
/home/correaa/soft/yaml-archive/src/boost/archive/basic_yaml_oarchive.hpp:93:9:   required from ‘void boost::archive::basic_yaml_oarchive<Archive>::save_override(const boost::serialization::nvp<T>&) [with T = const boost::array<A, 10>; Archive = boost::archive::yaml_oarchive]’
/usr/include/boost/archive/detail/interface_oarchive.hpp:70:9:   required from ‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator<<(const T&) [with T = boost::serialization::nvp<const boost::array<A, 10> >; Archive = boost::archive::yaml_oarchive]’
/home/correaa/soft/yaml-archive/test/io_fixture.hpp:17:18:   required from ‘io_fixture::outputter& io_fixture::outputter::operator<<(const T&) [with T = boost::serialization::nvp<const boost::array<A, 10> >]’
/home/correaa/soft/yaml-archive/test/arrays.cpp:116:21:   required from here
/usr/include/boost/serialization/access.hpp:116:11: error: ‘class boost::array<A, 10>’ has no member named ‘serialize’
  116 |         t.serialize(ar, file_version);
      |         ~~^~~~~~~~~
```

This happens after `cmake` gives no error:

```
$ cmake .. -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   serialization
--   wserialization
-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/correaa/soft/yaml-archive/build
$ cmake --build . --target install
```

**Comment by correaa** [comment]
I disabled all the tests involving `std::array` and `boost::array`. Now the library compiles but it doesn't link:

```
[ 20%] Linking CXX executable test_yaml-archive_yml
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libboost_wserialization.a(basic_text_wiprimitive.o): in function `boost::archive::basic_text_iprimitive<std::basic_istream<wchar_t, std::char_traits<wchar_t> > >::~basic_text_iprimitive()':
(.text._ZN5boost7archive21basic_text_iprimitiveISt13basic_istreamIwSt11char_traitsIwEEED2Ev[_ZN5boost7archive21basic_text_iprimitiveISt13basic_istreamIwSt11char_traitsIwEEED5Ev]+0x61): undefined reference to `vtable for boost::archive::codecvt_null<wchar_t>'
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libboost_wserialization.a(basic_text_wiprimitive.o): in function `boost::archive::basic_text_iprimitive<std::basic_istream<wchar_t, std::char_traits<wchar_t> > >::basic_text_iprimitive(std::basic_istream<wchar_t, std::char_traits<wchar_t> >&, bool)':
(.text._ZN5boost7archive21basic_text_iprimitiveISt13basic_istreamIwSt11char_traitsIwEEEC2ERS5_b[_ZN5boost7archive21basic_text_iprimitiveISt13basic_istreamIwSt11char_traitsIwEEEC5ERS5_b]+0x70): undefined reference to `vtable for boost::archive::codecvt_null<wchar_t>'
/usr/bin/ld: (.text._ZN5boost7archive21basic_text_iprimitiveISt13basic_istreamIwSt11char_traitsIwEEEC2ERS5_b[_ZN5boost7archive21basic_text_iprimitiveISt13basic_istreamIwSt11char_traitsIwEEEC5ERS5_b]+0x18f): undefined reference to `vtable for boost::archive::codecvt_null<wchar_t>'
collect2: error: ld returned 1 exit status
gmake[2]: *** [test/narrow/CMakeFiles/test_yaml-archive_yml.dir/build.make:1183: test/narrow/test_yaml-archive_yml] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:206: test/narrow/CMakeFiles/test_yaml-archive_yml.dir/all] Error 2
gmake: *** [Makefile:141: all] Error 2

```

**Comment by kd8azz** [comment]
I fixed this build failure in https://github.com/kd8azz/yaml-archive/commit/124f15bfec82da33a3773e23158ba085d025b52c , but half of the tests fail.

**Comment by correaa** [comment]
Thank you very much. 

BTW, in the midtime I developed this YAML archive serialization. 
https://gitlab.com/correaa/boost-archive-yml

It might have limited capabilities though: I never test it too much with reference counting and pointer serialization. The advantage is that it is header only.
